<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <Version>0.1.0</Version>
        <Authors>NuclearPowered</Authors>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
        <TargetLatestRuntimePatch>true</TargetLatestRuntimePatch>
        <ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch>true</ResolveAssemblyReferenceIgnoreTargetFrameworkAttributeVersionMismatch>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <DisableUnmanagedBindingResolution>true</DisableUnmanagedBindingResolution>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Reactor\Reactor.csproj" Private="false" />
        <PackageReference Include="BenchmarkDotNet" Version="0.13.10" />
    </ItemGroup>

    <Import Project="../AmongUs.props" />
</Project>
